stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - build
  image: docker:19.03.12
  before_script:
    - CI_REGISTRY_IMAGE="$CI_REGISTRY/$CI_PROJECT_NAME"
    - IMAGE_TAG="$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY
    - echo $IMAGE_TAG
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker tag $IMAGE_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main

deploy:
  stage: deploy
  tags:
    - deploy
  image: docker:19.03.12
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker-compose -f docker-compose.yml up -d
  only:
    - main
