apiVersion: v1
kind: Namespace
metadata:
  name: webhook-system
  labels:
    app.kubernetes.io/name: core-webhook-module
    app.kubernetes.io/component: namespace
    app.kubernetes.io/managed-by: kubectl
